
version: 2

models:
- name: transform
  columns:
    - name: metric_value
      tests:
      - not_null
      # - unique
    - name: time_dimension
      tests:
        - accepted_values:
            values: ['day', 'week', 'month', 'month_3']
